### ISSUE TITLE
Unable to Get Pretrained Model 

### ISSUE THREAD

**Issue by akumar48** [shkarupa-alex/tfreplknet#1]
I ran the following commands in python 3.9.10:
```from tfreplknet import RepLKNetB224In1k  # + 4 other variants and input preprocessing

model = RepLKNetB224In1k()  # by default will download imagenet{1k, 21k}-pretrained weights
```

and got back this error.
```Traceback (most recent call last):
  File "/home/sarvision/Desktop/rpknet/tfreplknet/../../openrpk.py", line 1, in <module>
    from tfreplknet import RepLKNetB224In1k  # + 4 other variants and input preprocessing
  File "/home/sarvision/.pyenv/versions/coral/lib/python3.9/site-packages/tfreplknet/__init__.py", line 1, in <module>
    from tfreplknet.model import RepLKNet, RepLKNetB, RepLKNetL, RepLKNetXL
  File "/home/sarvision/.pyenv/versions/coral/lib/python3.9/site-packages/tfreplknet/model.py", line 5, in <module>
    from keras.utils import data_utils, layer_utils
ImportError: cannot import name 'data_utils' from 'keras.utils' (/home/sarvision/.pyenv/versions/coral/lib/python3.9/site-packages/keras/utils/__init__.py)
```
Any help would be appreciated. Let me know if you need more information.
```
       _,met$$$$$gg.          sarvision@sarvision 
    ,g$$$$$$$$$$$$$$$P.       ------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) aarch64 
 ,$$P'              `$$$.     Host: Raspberry Pi 5 Model B Rev 1.0 
',$$P       ,ggs.     `$$b:   Kernel: 6.6.28+rpt-rpi-2712 
`d$$'     ,$P"'   .    $$$    Uptime: 2 hours, 11 mins 
 $$P      d$'     ,    $$P    Packages: 2051 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 2560x1440 
 Y$$.    `.`"Y$$$$P"'         DE: LXDE 
 `$$b      "-.__              WM: Openbox 
  `Y$$                        Theme: PiXflat [GTK3] 
   `Y$$.                      Icons: PiXflat [GTK3] 
     `$$b.                    Terminal: lxterminal 
       `Y$$b.                 Terminal Font: Monospace 10 
          `"Y$b._             CPU: (4) @ 2.400GHz 
              `"""            Memory: 888MiB / 8052MiB 
```

**Comment by shkarupa-alex** [comment]
Change >= to == and install exact versions https://github.com/shkarupa-alex/tfreplknet/blob/master/requirements.txt
